[profile.default]
solc = "0.8.20"
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "src/=src/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

[fmt]
line_length = 89
tab_width = 2
number_underscore = "thousands"
wrap_comments = true
